<?php
/**
 * @file voipsetup.module
 */ 

/**
 * Implementation of hook_enable().
 */
function voipsetup_enable() {
  $module_list = array(
    // CCK
    'content',
    'fieldgroup',
    'filefield',
    'imagefield', 
    'nodereference',
    'number',
    'optionwidgets',
    'text',
    // Date/time
    'date',
    'date_api',
    'date_timezone',
    // Development
    'devel',
    // Features
    'features', 
    // Other
    'advanced_help',
    // SWF Tools 
    'swftools',
    // Views
    'views',
    'views_bonus_export',
    'views_ui',
    // Voip Drupal
    'voip',
    'voipcall',
    'voipscriptui',
    'voiptwilio',
    // Voip Drupal contrib
//    'callblast',
//    'calllist',
    'clicktocall',
    'messaging_voip',
    'voipnumber',
    // Audiofield-related
    'audioconverter',
    'audiorecorderfield',
    'phonerecorderfield'
  );
  module_enable($module_list);
}
